[tool.poetry]
name = "lang-gizmo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
sse-starlette = "^1.6.5"
tomli-w = "^1.0.0"
uvicorn = "^0.23.2"
fastapi = "^0.103.2"
langserve = ">=0.0.16"
gizmo-agent = {path = "packages/gizmo-agent", develop = true}
agent-executor = {path = "packages/agent-executor", develop = true}

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.23.2"
pygithub = "^2.1.1"
langchain = {path = "../../langchain/libs/langchain", develop = true}
langserve = {path = "../../langserve", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
